### ISSUE TITLE
feat: elastic index cleanup when flow is down

### ISSUE THREAD

**Issue by IyadhKhalfallah** [jina-ai/now#1127]
In the previous implementation of the ES indexer logic, the lifecycle of the data was tied to the flow itself. Thus, the data will disappear when we destroy the flow and that is not convenient. 
Thankfully, in the new es-index-manager implementation, we could solve this problem by externalizing the logic from the flow's lifecycle. Nevertheless, the problem we would have in this case is that the indices will persist forever and that might cause a big problem (in cost and performance).

Hint:
- Link a script to remove the index when the flow is down (we also might want to map each index to the flow ID)

@girishc13 @violenil maybe you can give more insights about this

**Comment by girishc13** [comment]
@IyadhKhalfallah The index should ideally be removed if a Flow gets deleted. However the current operator might not handle all error scenarios that occurs during a Flow deletion process. We can create a daemon task on the es operator that can periodically check for unused indices and delete them. This process needs some careful coordination to identify the unused indices.

**Comment by IyadhKhalfallah** [comment]
> @IyadhKhalfallah The index should ideally be removed if a Flow gets deleted. However the current operator might not handle all error scenarios that occurs during a Flow deletion process. We can create a daemon task on the es operator that can periodically check for unused indices and delete them. This process needs some careful coordination to identify the unused indices.

Good idea, I think this ticket needs to be refined accordingly. We need to define:
- What is the definition of an unused index?
- What are the errors that can happen in the flow deletion process (and how do we handle them case by case)
- Based on what do we define the period of the daemon?

Also, IMO this should block the task of integrating now repo with es-index-manager since it can create a huge traffic (like we faced with flows) @florian-hoenicke

**Comment by girishc13** [comment]
@IyadhKhalfallah I'm not sure that you understood the existing auto delete feature. The index will be deleted when the Flow gets deleted. There might be some edge cases that we need to handle. Also @violenil must have created tickets to refactor the es-index-manager to target different ES clusters in order to separate CI and prod deployments.

- What is the definition of an unused index?
The ES api key contains the deployment metadata using which the can be used to check if the deployment exists or not. Non existing deployment don't need an index.

What are the errors that can happen in the flow deletion process (and how do we handle them case by case)?
- This is hard to define exactly but a few scenarios come to mind:
  - Somebody applied the [playbook](https://www.notion.so/Incident-Playbook-14e3b5f583a04fe5ae38dce275f04077) to manually delete the `finalizer` to unblock a flow deletion or handle an incident.
  - The es-index-manager pod was not running when the Flow got deleted.
  - There was a connection error to the elasticsearch cluster which prevented the index deletion. 

Based on what do we define the period of the daemon?
The period can be defined based on the lifecycle of flows. The CI daemon can run frequently to clean up faster. Prod deployments live longer so the period can be longer.

**Comment by violenil** [comment]
https://github.com/jina-ai/es-index-manager/pull/14

**Comment by violenil** [comment]
Relevant PR: https://github.com/jina-ai/es-index-manager/pull/14

**Comment by girishc13** [comment]
The es-index-manager is being deployed to more than one EKS cluster but uses only one ES cluster. This prevents the automatic clean up job because one EKS cluster cannot list of the deployment running in the other EKS cluster which leads to deletion of required indices. This ticket will need to be revisted later.
