### ISSUE TITLE
start failure

### ISSUE THREAD

**Issue by mashuaitop** [jina-ai/now#134]
I failed to start jina-now according to the tutorial, the choices were custon, create new, local (Kubernetes in Docker), Use Sandbox to save memory: yes, and then an error was reported,`FileNotFoundError: [Errno 2] No such file or directory: '/Users/dev/.cache/jina-now/kind'`. What's the problem? Is it a problem with my k8s cluster?

**Comment by makram93** [comment]
Hi @mashuaitop, 
Thank you for trying out Jina NOW. To setup the cluster on your machine, NOW tries to install [kubectl](https://kubernetes.io/docs/tasks/tools/) and [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) in the cache folder, if it is not installed already on your system. As you see in this screenshot below, since I did not have kind install, when I run `jina now start` it first installs kind at `~/.cache/jina-now`

<img width="888" alt="image" src="https://user-images.githubusercontent.com/6537525/165897427-03966806-978d-42e8-a785-9287a23acfa6.png">

---
Can you verify if kind is installed on your machine? If not, do you see a message similar to the above screenshot?
Can you also let me know your machine details? OS and arch

**Comment by florian-hoenicke** [comment]
@mashuaitop thanks again for reporting the issue.
In case the procedure @makram93 described will not lead to the desired results, feel free to reopen/ recreate the issue.
