### ISSUE TITLE
feat: pixel tracking on playground

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/now#232]
- Include google analytics in hosted playground

**Comment by fogx** [comment]
if we do this we need to also add a privacy widget :(
And if we are already adding a privacy widget, we should also consider adding [hotjar](https://www.hotjar.com/). Its really nice.

**Comment by fogx** [comment]
add utm code to link on readme

**Comment by fogx** [comment]
For the pixel tracking we need to add a js snippet to the streamlit app. Here are two threads regarding the topic.
We'll add a google tag manager snippet, because we can use it to modify events and add integrations without having to modify the source code. Then we can add a hotjar integration on top.

https://medium.com/@stevernewman/how-to-add-google-analytics-to-a-streamlit-application-face3c9f8f97
https://discuss.streamlit.io/t/how-to-add-google-analytics-or-js-code-in-a-streamlit-app/1610/35

For the cookie consent, we will use a cookie consent tool - probably cookiebot. However, they require us to define a domain name, which we don't have right now. 
If you have any solutions, please implement. Otherwise i would suggest we skip the consent banner for the next week and just add tracking without it. Then i can fix it when i'm back.

GTM snippet:
https://developers.google.com/tag-manager/quickstart

 Paste this code as high in the <head> of the page as possible: 
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MKCJBDS');</script>
<!-- End Google Tag Manager -->
```
 Additionally, paste this code immediately after the opening <body> tag: 
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKCJBDS"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by fogx** [comment]
@fogx 
- [ ] Change GTM account to use jina.ai general account and update the snippet.
- [ ] test if traffic is detected properly

**Comment by fogx** [comment]
i've updated the tracking ID and paired with @slettner to test the snippet. I need a public URL to use the debug tool to make sure though. @makram93 how are the cloud-hosted links updated?
