### ISSUE TITLE
NEST: end-to-end test

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/now#509]
put everything together and write an end-to-end test

**Comment by violenil** [comment]
UAC:

- [ ] `text-to-text-and-image` app runs in the end-to-end tests

**Comment by violenil** [comment]
Update:

- ran into a bug with FinetunerExecutor, `open_clip` dependency missing
- currently thinking about whether to use the external clip executor used by other apps (maybe more efficient especially for testing)
- finetuner team [implementing ](https://github.com/jina-ai/finetuner-core/pull/336) a `build_model` function that we can use to avoid finetuning during testing
  - basically just loads a zero-shot model with pretrained weights
- paired with @florian-hoenicke yesterday and realized for the BFF we need models and routers for the multi-modal app, I am currently in the process of implementing these

**Comment by violenil** [comment]
Update: encoding multi-modal documents with different encoders has turned out to be more difficult than expected. 

I have summarized my issues in [this notion document](https://www.notion.so/Multiple-Encoders-One-Flow-11c9d64e8c714e878ca0a0fe5f640330). 

In a nutshell, we want to host multiple encoders in one flow, but only want them to encode specific documents, and only on specific actions (indexing vs querying). For example, our textual query should be encoded by both SBert and CLIP-text, while the text component of our indexed documents should only be encoded by SBert. There are ways to specify filter conditions (eg. on `modality: text`) but these filters only work on root level, while our different modalities are found at chunk level. See the full report on the issue in the notion document. I am looking forward to comments and suggestions!
